---
title: "Descriptive analysis (imputed)"
author: "Jae Yeon Kim"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

# Load packages 

```{r}
if (!require(pacman)) install.packages("pacman")

pacman::p_load(tidyverse, # tidyverse 
               plm, # panel data analysis
               clubSandwich, # robust SEs
               here, # computational reproducibility 
               glue, # gluing objects and strings 
               tidylog, # logging analysis
               naniar, # missing data 
               zeallot, # multiple assignments 
               readxl, 
               ggpubr,
               hrbrthemes, 
               wesanderson,
               broom, 
               jtools, 
               patchwork, 
               broom.mixed, 
               estimatr, 
               stargazer,
               DeclareDesign,
               sensemakr,
               mice,
               usmap,
               janitor,
               modelsummary, 
               flextable,
               officer,
               extrafont,
               gt,
               bootstrap,
               lme4,
               clipr)

source(here("functions/utils.r"))
source(here("functions/theme.R"))

ggplot2::theme_set(theme_bw())

# no scientific notation
options(scipen = 999)
```

# Load files 

```{r message = FALSE}
df <- read_csv(here("processed_data", "panel_data_cleaned.csv"))[,-c(1:2)]

df2 <- subset(df, wave == 2)
```

# Summarize by group 

## Different partisans

```{r}
dodge <- position_dodge(width=0.9)

party1 <- df %>%
    group_by(wave, party.id) %>%
    count() %>%
    ggplot(aes(x = wave, y = n, fill = party.id)) +
    geom_col(position = dodge)

party2 <- df %>%
    mutate(party.id = if_else(party.id %in% c("Democrat", "Republican") | is.na(party.id), party.id, "Independent or Other")) %>%
    group_by(wave, party.id) %>%
    count() %>%
    ggplot(aes(x = wave, y = n, fill = party.id)) +
    geom_col(position = dodge)

party1 / party2 + plot_annotation(tag_levels = )
```

```{r}
var.list <- names(df)[str_detect(names(df), "disc")][c(1, 3)]

# rescale the discrimination perception variables
df$apa.discrim.rona <- df$apa.discrim.rona - .5
df$gendiscrim <- df$gendiscrim - .5

var.list <- c(var.list, c("linkedfate", "idimport", "asnpride", "rona.behav.sneeze", "rona.behav.language", "rona.behav.walk", "rona.behav.transit", "rona.behav.other", "rona.behav.nochange", "rona.index", "X2020likelyvote", "biden", "DEM", "DEM.strong", "GOP", "GOP.strong", "ronaunfair", "ronaunfairasian", "rona.apa.mistreat", "apa.responsible", "apa.have.rona", "apa.harassment", "whiteaffect", "blackaffect", "latinoaffect", "asianaffect"))

group_sum <- purrr::map_dfr(seq(var.list), group_mean) %>%
    mutate(variable = rep(var.list, each = 3)) %>%
    filter(!is.na(mean)) 
```

## Discrimination perception 

```{r}
group_sum %>%
    filter(str_detect(variable, "disc")) %>%
    mutate(variable = recode(variable, 
                             "apa.discrim.rona" = "COVID-19 discrimination",
                             "gendiscrim" = 
                                 "General discrimination")) %>%
    ggplot(aes(x = glue("{factor(wave_fac)} 2020"), y = mean,
               ymax = mean + ci_high, 
               ymin = mean - ci_low)) +
        geom_errorbar() +
        geom_col(alpha = 0.5) +
        #ggrepel::geom_text_repel(aes(label = glue("{round(mean, 3)*100}%", position = dodge), width = 0.25, col = "red")) +
        facet_wrap(~variable) +
        labs(title = "Changes in discrimination perception",
            x = "", y = "Average response") +
        geom_hline(yintercept = 0,  linetype = 'dotted', col = 'red', size = 1) +
        theme(legend.position = "none")
ggsave(here("outputs", "disc.perception.png"), 
       width = 10, 
       height = 7) +
  ylim(c(-.5, .5))

ggsave(here("outputs", "diff.png"))
```

```{r}
gen_density <- df %>%
  ggplot(aes(gendiscrim)) +
    geom_density() +
    facet_wrap(~wave_fac) +
    labs(x = "Response",
         y = "Density",
         title = "General discrimination") +
    geom_vline(xintercept = 0,  linetype = 'dotted', col = 'red', size = 1)

rona_density <- df %>%
  ggplot(aes(apa.discrim.rona)) +
    geom_density() +
    facet_wrap(~wave_fac) +
    labs(x = "Response",
         y = "Density",
         title = "COVID-19 discrimination") +
    geom_vline(xintercept = 0,  linetype = 'dotted', col = 'red', size = 1)

(gen_density / rona_density) + plot_annotation(tag_levels = "A")

ggsave(here("outputs", "density.png"))
```

```{r}
df$proxy <- rep(subset(df, wave == 1)$gendiscrim, 3)
```

```{r}
plot_w12 <- df %>%
    filter(wave %in% c(1,2)) %>%
    group_by(proxy) %>%
    summarise(mean = mean(apa.discrim.rona, na.rm = TRUE),
                  ci_high = ci.high(apa.discrim.rona),
                  ci_low = ci.low(apa.discrim.rona)) %>%
    mutate(group = 2)

plot_w13 <- df %>%
    filter(wave %in% c(1,3)) %>%
    group_by(proxy) %>%
    summarise(mean = mean(apa.discrim.rona, na.rm = TRUE),
                  ci_high = ci.high(apa.discrim.rona),
                  ci_low = ci.low(apa.discrim.rona)) %>%
    mutate(group = 3)

plot_w123 <- bind_rows(plot_w12, plot_w13)
```


```{r}
plot_w123 %>%
    ggplot(aes(x = factor(proxy), y = mean,
               ymax = mean + ci_high, 
               ymin = mean - ci_low,
               col = factor(group))) +
        geom_pointrange() +
        #ggrepel::geom_text_repel(aes(label = round(mean, 2), y = mean), size = 5, vjust = -.5) +
        labs(x = "Response to general discrimination Q in W1", 
             y = "Average response to COVID-19 discrimination Q in W2 & W3",
             col = "Wave") +
        geom_hline(yintercept = 0,  linetype = 'dotted', col = 'red', size = 1) +
#        facet_wrap(~group) +
        #scale_fill_brewer(palette = "Set1") +
        #theme(legend.position =  "down") +
  ylim(c(-.5, .5)) 

ggsave(here("outputs", "disc.wave.png"), height = 6)
```

## Affect 

```{r}
group_sum %>%
  filter(wave_fac != "November") %>% 
  filter(str_detect(variable, "affect")) %>%
  mutate(variable = recode(variable, 
                           "asianaffect" = "Asian",
                           "latinoaffect" = "Latino",
                           "blackaffect" = "Black",
                           "whiteaffect" = "White")) %>%
  mutate(mean = round(mean, 2)) %>%
  ggplot(aes(x = wave_fac, y = mean,
               ymax = mean + ci_high, 
               ymin = mean - ci_low,
             col = variable)) +
        geom_pointrange() +
        labs(x = "", y = "Average response",
            col = "Affect") +
        geom_hline(yintercept = 3.5, linetype = 'dotted', col = 'red', size = 1) +
        scale_colour_brewer(palette = "Set1")
ggsave(here("outputs", "affect.png"))
```

```{r}
group_sum %>%
    filter(wave_fac == "May") %>% 
    filter(str_detect(variable, "rona")) %>%
    filter(!str_detect(variable, "apa|nochange|2020|biden|DEM|GOP|fair|affect")) %>%
    mutate(variable = recode(variable, 
                             "rona.behav.sneeze" = "Avoid coughing/sneezing",
                             "rona.behav.language" = 
                             "Avoid speaking Asian language",
                             "rona.behav.walk" = "Avoid walking in neighborhoods",
                             "rona.behav.transit" = "Avoid public transporation",
                             "rona.behav.other" = "Others",
                             "rona.index" = "Average response")) %>%
  mutate(mean = mean*100) %>%
    ggplot(aes(x = factor(variable), y = mean,
               ymax = mean + ci_high, 
               ymin = mean - ci_low)) +
        geom_pointrange() +
        ggrepel::geom_text_repel(aes(label = paste0(round(mean, 2), "%"))) +
        labs(title = "COVID-19 related marginalized experience (Wave 2)",
            x = "", y = "Percentage") +
        coord_flip() +
        scale_y_continuous(labels = ~paste0(., "%"))
ggsave(here("outputs", "rona_behave.png"), width = 10)
```

```{r}
group_sum %>%
    #filter(wave_fac == "May") %>% 
    filter(str_detect(variable, "ronaunfair")) %>%
    mutate(variable = recode(variable, 
 "ronaunfairasian" = "Experienced COVID discrimination due to race",
 "ronaunfair" = "Experienced COVID-19 discrimination")) %>%
  mutate(mean = mean*100) %>%
    ggplot(aes(x = wave_fac, y = mean,
               ymax = mean + ci_high*100, 
               ymin = mean - ci_low*100)) +
        geom_pointrange() +
        ggrepel::geom_text_repel(aes(label = paste0(round(mean, 2), "%"))) +
        labs(title = "COVID-19 related unfair treatment",
            x = "", y = "Percentage") +
        facet_wrap(~variable) +
        scale_y_continuous(labels = ~paste0(., "%"))
ggsave(here("outputs", "rona_fair.png"), width = 12)
```

```{r}
# Lost job 
lost_job_pct <- sum(!is.na(df %>%
  filter(wave == 2) %>% 
  pull(lostjob)))/(df %>% filter(wave == 2) %>% nrow()) %>%
  round(2)
  
round(lost_job_pct, 4) * 100 
```

5.57% participants in the wave 2 lost jobs. 

```{r}
income_reduction_pct <- sum(!is.na(df %>%
  filter(wave == 2) %>% 
  pull(incomereduc)))/(df %>% filter(wave == 2) %>% nrow()) %>%
  round(2)
round(income_reduction_pct, 4) * 100
```

```{r}
df2 <- df2 %>%
    mutate(apa.discrim.rona = replace_na(apa.discrim.rona, 0),
           lostjob = replace_na(lostjob, 0),
           incomereduc = replace_na(incomereduc, 0),
           ronaunfairasian = replace_na(ronaunfairasian, 0),
           rona.apa.mistreat = replace_na(rona.apa.mistreat, 0))

mod1 <- lm(apa.discrim.rona ~ lostjob + incomereduc, data = df2) 
mod2 <- lm(apa.discrim.rona ~ ronaunfairasian, data = df2)
mod3 <- lm(apa.discrim.rona ~ rona.apa.mistreat, data = df2)

set.seed(1234)
modelsummary(list(`Hardship` = mod1, `Experience` = mod2, `Witnesing` = mod3),
             fmt = 4,
             coef_omit = "Intercept",
             statistic = "p.value",
             stars = TRUE,
             vcov = "bootstrap", R = 1000,
             output = here("outputs", "reg_measure.docx")) 
```

## Party ID

```{r}
dodge <- position_dodge(width=0.9)

group_sum %>%
    filter(variable %in% c("DEM", "GOP")) %>%
    ggplot(aes(x = glue("{factor(wave_fac)} 2020"), y = mean,
               ymax = mean + ci_high, 
               ymin = mean - ci_low)) +
        geom_errorbar() +
        geom_col(alpha = 0.5) +
        #ggrepel::geom_text_repel(aes(label = glue("{round(mean, 3)*100}%", position = dodge), width = 0.25, col = "red")) +
        facet_wrap(~variable) +
        labs(title = "Changes in discrimination perception",
            x = "", y = "Average response") +
        geom_hline(yintercept = 0,  linetype = 'dotted', col = 'red', size = 1) +
        theme(legend.position = "none")
ggsave(here("outputs", "disc.perception.png"), 
       width = 10, 
       height = 7) +
  ylim(c(-.5, .5))

ggsave(here("outputs", "party_diff.png"))
```

# Regression analysis

## Imputation

```{r}
df_na_sum <- df %>%
  #filter(wave != 1) %>%
  select(X2020likelyvote, biden, gendiscrim, apa.discrim.rona, usborn, edu, income, DEM, GOP, age, male, wave, korean, chinese) %>%
  map_dfr(~is.na(.) %>% mean())
```

```{r}
imp <- mice(
  df %>%
   #filter(wave != 1) %>%
    select(gendiscrim, apa.discrim.rona, usborn, edu, income, DEM, GOP, age, male, wave, korean, chinese),
    seed = 1234, # for reproducibility
    m = 5, # the number of imputations
    maxit = 10, # the max number of iterations 
    method = "pmm", # predictive mean method
    print = FALSE)

densityplot(imp, layout = c(1,2))

imputed <- mice::complete(imp)
```

```{r}
# Replace with the imputed values 


df$apa.discrim.rona[665:nrow(df)] <- 
imputed$apa.discrim.rona

df$gendiscrim <- 
imputed$gendiscrim

df$DEM <- 
imputed$DEM

df$GOP <- 
imputed$GOP

df$age <- 
imputed$age

df$X2020likelyvote
```

## Panel data analysis

```{r}
df13 <- subset(df, wave %in% c(1,3))

df12 <- subset(df, wave %in% c(1,2))

panel_mods12 <- list(

    "DEM FE" = plm(DEM ~ gendiscrim + usborn + edu + age + male + chinese + korean, data=df12, index = c("pid", "wave"), model = "within"),  #fixed model

    "DEM RE" = plm(DEM ~ gendiscrim + usborn + edu + age + male + chinese + korean, data=df12, index = c("pid", "wave"), model = "random"),  #random model

    "GOP FE" = plm(GOP ~ gendiscrim + usborn + edu + age + male + chinese + korean, data=df12, index = c("pid", "wave"), model = "within"),  #fixed model

    "GOP RE" = plm(GOP ~ gendiscrim + usborn + edu + age + male + chinese + korean, data=df12, index = c("pid", "wave"), model = "random"),  #random model

    "Independent FE" = plm(independent ~ gendiscrim + usborn + edu + age + male + chinese + korean, data=df12, index = c("pid", "wave"), model = "within"),  #fixed model

    "Independent RE" = plm(independent ~ gendiscrim + usborn + edu + age + male + chinese + korean, data=df12, index = c("pid", "wave"), model = "random")  #random model

    )
```

```{r}
panel_mods13 <- list(

    "DEM FE" = plm(DEM ~ gendiscrim + usborn + edu + income + age + male + chinese + korean, data=df13, index = c("pid", "wave"), model = "within"),  #fixed model

    "DEM RE" = plm(DEM ~ gendiscrim + usborn + edu + income + age + male + chinese + korean, data=df13, index = c("pid", "wave"), model = "random"),  #random model

    "GOP FE" = plm(GOP ~ gendiscrim + usborn + edu + income + age + male + chinese + korean, data=df13, index = c("pid", "wave"), model = "within"),  #fixed model

    "GOP RE" = plm(GOP ~ gendiscrim + usborn + edu + income + age + male + chinese + korean, data=df13, index = c("pid", "wave"), model = "random"),  #random model

    "Independent FE" = plm(independent ~ gendiscrim + usborn + edu + income + age + male + chinese + korean, data=df13, index = c("pid", "wave"), model = "within"),  #fixed model

    "Independent RE" = plm(independent ~ gendiscrim + usborn + edu + income + age + male + chinese + korean, data=df13, index = c("pid", "wave"), model = "random")  #random model

    )

table_mods12 <- modelsummary(panel_mods12, estimate = "p.value", output = "gt", vcov = "robust")

table_mods13 <- modelsummary(panel_mods13, estimate = "p.value", output = "gt", vcov = "robust")

table_mods12
table_mods13
```

```{r}
fe.mod <- plm(independent ~ gendiscrim + apa.discrim.rona + usborn + edu + income + age + male, data=df, index = c("pid", "wave"), model = "within")  #fixed model

re.mod <- plm(independent ~ gendiscrim + apa.discrim.rona + usborn + edu + income + age + male, data=df, index = c("pid", "wave"), model = "random")  #random model

phtest(fe.mod, re.mod) #Hausman test
```

## Likely to vote 

```{r}
# rescale the discrimination perception variables
df$apa.discrim.rona <- df$apa.discrim.rona + .5
df$gendiscrim <- df$gendiscrim + .5

df$proxy <- rep(subset(df, wave == 1)$gendiscrim, 3)
df$prior[df$proxy == 0.5] <- "Middle"
df$prior[df$proxy < 0.5] <- "Low"
df$prior[df$proxy > 0.5] <- "High"
```

```{r}
model.outs <- cal_model_outputs(df)
model.outs.low <- cal_model_outputs(df %>%
                                      filter(prior == "Low"))
model.outs.middle <- cal_model_outputs(df %>%
                                      filter(prior == "Middle"))
model.outs.high <- cal_model_outputs(df %>%
                                      filter(prior == "High"))
```

### Main 

```{r}
models <- list(

"Model 1" = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + factor(wave), data = df),

"Model 2" = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave), data = df),

"Model 3" = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = df))

modelsummary(models,
             fmt = 3,
             coef_omit = "Intercept",
             #statistic = c("p = {p.value}"),
             stars = TRUE, 
             output = here("outputs", "reg_tb1.docx"),
             coef_rename = 
                c("gendiscrim" = "General discrimination",
                   "apa.discrim.rona" = "COVID-19 discrimination",
                   "usborn" = "US born",
                   "edu" = "Education",
                   "income" = "Income",
                   "DEM" = "Democratic Party",
                   "GOP" = "Republican Party",
                   "age" = "Age",
                   "male" = "Male",
                   "factor(wave)3" = "Wave 3",
                   "korean" = "Korean",
                   "chinese" = "Chinese"),
             vcov = "HC2",
             cluster = "state")
```

```{r}
sense.out <- sensemakr(model = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = df),
          treatment = "apa.discrim.rona", 
          benchmark_covariates = "usborn",
          kd = 1:3, 
          ky = 1:3, 
          q = 1)

main.sense <- summary(sense.out) %>%
    flextable() %>%
    set_table_properties(layout = "autofit", width = .8)

main.tmp <- tempfile(fileext = ".docx")

# Create a docx file
read_docx() %>% 
  body_add_flextable(main.sense) %>% 
  print(target = main.tmp)

browseURL(main.tmp)
```

### Sub

```{r}
sub.models <- list(
"High Discrimination Pre-COVID" = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "High")),
            
"Middle Discrimination Pre-COVID" = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "Middle")),
            
"Low Discrimination Pre-COVID" = lm(X2020likelyvote ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "Low")))

modelsummary(sub.models,
             fmt = 3,
             coef_omit = "Intercept",
             #statistic = c("p = {p.value}"),
             stars = TRUE, 
             output = here("outputs", "reg_tb_sub1.docx"),
             coef_rename = 
                c("gendiscrim" = "General discrimination",
                   "apa.discrim.rona" = "COVID-19 discrimination",
                   "usborn" = "US born",
                   "edu" = "Education",
                   "income" = "Income",
                   "DEM" = "Democratic Party",
                   "GOP" = "Republican Party",
                   "age" = "Age",
                   "male" = "Male",
                   "factor(wave)3" = "Wave 3",
                   "korean" = "Korean",
                   "chinese" = "Chinese"),
             vcov = "HC2",
             cluster = "state")
```

```{r}
sense_series <- c(sub.models[[2]] %>% 
    tidy() %>% 
    filter(term == "apa.discrim.rona") %>%
    select(estimate) %>%
    pull(estimate),

run_sense(sub.models[[2]]) %>% 
    tibble() %>%
    select(contains("Adjusted Estimate")) %>%
    pull(`Adjusted Estimate`))

bench <- sub.models[[2]] %>% 
    tidy() %>% 
    filter(term == "DEM") %>%
    select(estimate) %>%
    pull(estimate)

1 - (sense_series[1] - sense_series[4])/sense_series[1]
bench
1 - (sense_series[1] - sense_series[4])/sense_series[1] > bench

run_sense(sub.models[[2]]) %>% 
    tibble() %>%
    gt()
```

## Biden candidacy

### Partisanship 

```{r}
# partisan biden support 
df %>%
  filter(wave == 3) %>%
  filter(!is.na(party.id)) %>%
  group_by(party.id) %>%
  summarize(mean = mean(biden, na.rm = T))
```

### Main 

```{r}
biden.models <- list(

"Model 1" = glm(biden ~ gendiscrim + apa.discrim.rona + factor(wave), data = df, family = binomial),

"Model 2" = glm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave), data = df, family = binomial),

"Model 3" = glm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = df, family = binomial))
```

```{r}
modelsummary(biden.models,
             exponentiate = TRUE,
             fmt = 3,
             coef_omit = "Intercept",
             #statistic = c("p = {p.value}"),
             stars = TRUE, 
             output = here("outputs", "reg_tb2.docx"),
             coef_rename = 
                c("gendiscrim" = "General discrimination",
                   "apa.discrim.rona" = "COVID-19 discrimination",
                   "usborn" = "US born",
                   "edu" = "Education",
                   "income" = "Income",
                   "DEM" = "Democratic Party",
                   "GOP" = "Republican Party",
                   "age" = "Age",
                   "male" = "Male",
                   "factor(wave)3" = "Wave 3",
                   "korean" = "Korean",
                   "chinese" = "Chinese"),
             vcov = c("HC0"),
             cluster = "state")
```

```{r}
sense.out.biden <- sensemakr(model = lm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = df),
          treatment = "apa.discrim.rona", 
          benchmark_covariates = "usborn",
          kd = 1:3, 
          ky = 1:3, 
          q = 1)

biden.sense <- summary(sense.out.biden) %>%
    flextable() %>%
    set_table_properties(layout = "autofit", width = .8)

biden.tmp <- tempfile(fileext = ".docx")

# Create a docx file
read_docx() %>% 
  body_add_flextable(biden.sense) %>% 
  print(target = biden.tmp)

browseURL(biden.tmp)
```

```{r}
test.out <- lm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = df)

modelsummary(test.out, 
             fmt = 3,
             coef_omit = "Intercept",
             #statistic = c("p = {p.value}"),
             stars = TRUE)
```

### Sub

```{r}
sub.models <- list(
"High Discrimination Pre-COVID" = glm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "High"), family = binomial),
            
"Middle Discrimination Pre-COVID" = glm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "Middle"), family = binomial),
            
"Low Discrimination Pre-COVID" = glm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "Low"), family = binomial))
```

```{r}
modelsummary(sub.models,
             exponentiate = TRUE,
             fmt = 3,
             coef_omit = "Intercept",
             #statistic = c("p = {p.value}"),
             stars = TRUE, 
             output = here("outputs", "reg_tb_sub2.docx"),
             coef_rename = 
                 c("gendiscrim" = "General discrimination",
                   "apa.discrim.rona" = "COVID-19 discrimination",
                   "usborn" = "US born",
                   "edu" = "Education",
                   "income" = "Income",
                   "DEM" = "Democratic Party",
                   "GOP" = "Republican Party",
                   "age" = "Age",
                   "male" = "Male",
                   "factor(wave)3" = "Wave 3",
                   "korean" = "Korean",
                   "chinese" = "Chinese"),
             vcov = "HC0",
             cluster = "state")
```

```{r}
model <- lm(biden ~ gendiscrim + apa.discrim.rona + usborn + edu + income + DEM + GOP + age + male + factor(wave) + korean + chinese, data = subset(df, prior == "Middle"))

sense_series <- c(model %>% 
    tidy() %>% 
    filter(term == "apa.discrim.rona") %>%
    select(estimate) %>%
    pull(estimate),

run_sense(model) %>% 
    tibble() %>%
    select(contains("Adjusted Estimate")) %>%
    pull(`Adjusted Estimate`))

bench <- model %>% 
    tidy() %>% 
    filter(term == "DEM") %>%
    select(estimate) %>%
    pull(estimate)

1 - (sense_series[1] - sense_series[4])/sense_series[1]
bench
1 - (sense_series[1] - sense_series[4])/sense_series[1] > bench

run_sense(model) %>% 
    tibble() %>%
    gt()
```

## Correlates

```{r}
modelplot(lm(gendiscrim ~ usborn + edu + income + DEM + GOP + age + male, data = subset(df, wave == 1)),
          coef_omit = "Intercept",
          vcov = "HC2",
          coef_rename = 
                 c("usborn" = "US born",
                   "edu" = "Education",
                   "income" = "Income",
                   "DEM" = "Democratic Party",
                   "GOP" = "Republican Party",
                   "age" = "Age",
                   "male" = "Male")) +
    geom_vline(xintercept = 0, col = "red", linetype = "dashed") +
    theme_classic()

ggsave(here("outputs", "correlate_gen.png"))
```

```{r}
modelplot(lm(apa.discrim.rona ~ usborn + edu + income + DEM + GOP + age + male + wave_fac, data = subset(df, wave != 1)),
          coef_omit = "Intercept",
          vcov = "HC2",
          coef_rename = 
                 c("usborn" = "US born",
                   "edu" = "Education",
                   "income" = "Income",
                   "DEM" = "Democratic Party",
                   "GOP" = "Republican Party",
                   "age" = "Age",
                   "male" = "Male",
                   "wave_facNovember" = "Wave 3")) +
    geom_vline(xintercept = 0, col = "red", linetype = "dashed") +
    theme_classic()

ggsave(here("outputs", "correlate_covid.png"))
```